site_name: TrendingNow
site_url: https://totoantonio.github.io/TrendingNow/
site_author: totoantonio
site_description: "AI-Driven Trends in Gadgets & Technology"

repo_name: totoantonio/TrendingNow
repo_url: https://github.com/totoantonio/TrendingNow

copyright: "TrendingNow maintained by <a href=https://github.com/totoantonio>totoantonio</a>"

theme:
  name: "material"
  language: "en"
  font:
    text: "Poppins" # Specify the font for the text

  palette:
    primary: "white"
    accent: "white"
    scheme: TrendingNow
  logo: assets/favicon.png
  favicon: assets/favicon.png

  extra:
  social:
    image: assets/TrendingNow.png

  plugins:
    - search
    - meta
    - minify
    - social
  features:
    - navigation.footer
    - content.code.copy
    - previous_next

extra_css:
  - stylesheets/extra.css # Custom CSS file for additional styling if needed

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - attr_list

nav:
  - Whoami: AboutMe.md
  - Contact: Contact.md
  - What I Do: What I Do.md
