site_name: TrendingNow
site_url: https://totoantonio.github.io/TrendingNow/
site_description: Stay ahead with AI-driven insights on gadgets and technology! Discover the latest trends, reviews, and innovations shaping the future of tech in the USA. Explore AI-powered solutions for smarter living.
site_author: totoantonio
repo_name: totoantonio/TrendingNow
repo_url: https://github.com/totoantonio/TrendingNow
copyright: TrendingNow maintained by <a href=https://github.com/totoantonio>totoantonio</a>

theme:
  name: material
  language: en
  font:
    text: Poppins
  palette:
    primary: white
    accent: white
    scheme: TrendingNow
  logo: assets/favicon.png
  favicon: assets/favicon.png

plugins:
  - search
  - minify:
      minify_html: true
      minify_css: true
  - material/social:
      cards_dir: assets/social
      cards_layout_options:
        background_image: default_card.png

extra:
  navigation:
    footer: true
  code:
    copy: true
  site:
    previous_next: true
  material/social:
    cards:
      image: https://totoantonio.github.io/TrendingNow/assets/social/default_card.png

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - attr_list

nav:
  - Whoareus: index.md
  - Whoami: AboutMe.md
  - Whotoreach: Contact.md
  - Whataido: What I Do.md
